### ISSUE TITLE
apatite v 20.0.0 requires pip install ashes before it works

### ISSUE THREAD

**Issue by mcgyver5** [mahmoud/apatite#1]
I upgraded apatite to the latest version (20.0.0) and ran `$ apatite render`.  got the following error:
```
$ apatite render
Traceback (most recent call last):
  File "c:\users\mcgyv\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mcgyv\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mcgyv\AppData\Local\Programs\Python\Python37\Scripts\apatite.exe\__main__.py", line 5, in <module>
  File "c:\users\mcgyv\appdata\local\programs\python\python37\lib\site-packages\apatite\__main__.py", line 4, in <module>
    from .cli import main
  File "c:\users\mcgyv\appdata\local\programs\python\python37\lib\site-packages\apatite\cli.py", line 22, in <module>
    from ashes import AshesEnv
ModuleNotFoundError: No module named 'ashes'
```

so I ran pip install ashes and now it works.

**Comment by mcgyver5** [comment]
here is the output from a fresh apatite install.  It does not grab ashes but installs the other libraries listed in requirements.txt:
```
C:\users\pmooo414>pip install apatite
Collecting apatite
  Downloading https://files.pythonhosted.org/packages/c0/24/e32168070eadd198d77bb11cc21d0992205356c904a42cff9652b76a76f9/apatite-20.0.0.tar.gz
Collecting attrs (from apatite)
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting boltons (from apatite)
  Downloading https://files.pythonhosted.org/packages/da/53/87bd0ccbf59e760bd2817b5895cbed91b3e573732f8cc40ae299ff9bf886/boltons-20.0.0-py2.py3-none-any.whl (16
8kB)
    100% |################################| 174kB 311kB/s
Collecting face (from apatite)
  Downloading https://files.pythonhosted.org/packages/f8/bb/13a1d88bf619b376c41581336bdb819749e6b7877003e2340f7ee6c249fc/face-19.1.2-py2-none-any.whl
Collecting ruamel.yaml (from apatite)
  Downloading https://files.pythonhosted.org/packages/fa/90/ecff85a2e9c497e2fa7142496e10233556b5137db5bd46f3f3b006935ca8/ruamel.yaml-0.16.5-py2.py3-none-any.whl
 (123kB)
    100% |################################| 133kB 747kB/s
Collecting glom (from apatite)
  Downloading https://files.pythonhosted.org/packages/ff/1e/d065d2ec56a6ae82c78ab73eead582f106af4a3419d2581699d2bec768e9/glom-19.10.0-py2-none-any.whl (66kB)
    100% |################################| 71kB 623kB/s
Collecting hyperlink (from apatite)
  Downloading https://files.pythonhosted.org/packages/7f/91/e916ca10a2de1cb7101a9b24da546fb90ee14629e23160086cf3361c4fb8/hyperlink-19.0.0-py2.py3-none-any.whl
Collecting schema (from apatite)
  Downloading https://files.pythonhosted.org/packages/45/ae/a7e3cc8b885e681cbfee89d8d43dbc0168dbd033e2b2745eda6223477467/schema-0.7.1-py2.py3-none-any.whl
Collecting tqdm (from apatite)
  Downloading https://files.pythonhosted.org/packages/72/c9/7fc20feac72e79032a7c8138fd0d395dc6d8812b5b9edf53c3afd0b31017/tqdm-4.41.1-py2.py3-none-any.whl (56kB)

    100% |################################| 61kB 461kB/s
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" (from ruamel.yaml->apatite)
  Downloading https://files.pythonhosted.org/packages/97/f4/98dc93e36bfdaefa8edf5183fbf14a00439f48e5cd301e7c2954854b11c2/ruamel.yaml.clib-0.2.0-cp27-cp27m-win_a
md64.whl (115kB)
    100% |################################| 122kB 455kB/s
Collecting ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" (from ruamel.yaml->apatite)
  Downloading https://files.pythonhosted.org/packages/c4/ca/779dffdca6f1379c5dc4a15b08cc734aac3505e4c36b07376c9139a16db0/ruamel.ordereddict-0.4.14-cp27-cp27m-wi
n_amd64.whl
Requirement already satisfied: idna>=2.5 in c:\python27\lib\site-packages (from hyperlink->apatite)
Collecting contextlib2==0.5.5 (from schema->apatite)
  Downloading https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Building wheels for collected packages: apatite
  Running setup.py bdist_wheel for apatite ... done
  Stored in directory: C:\Users\pwtem47\AppData\Local\pip\Cache\wheels\94\90\42\9ecd8fe3fb3b68fa24ea5e6a40c547fcea4285e4168cbd2a1d
Successfully built apatite
Installing collected packages: attrs, boltons, face, ruamel.yaml.clib, ruamel.ordereddict, ruamel.yaml, glom, hyperlink, contextlib2, schema, tqdm, apatite
Successfully installed apatite-20.0.0 attrs-19.3.0 boltons-20.0.0 contextlib2-0.5.5 face-19.1.2 glom-19.10.0 hyperlink-19.0.0 ruamel.ordereddict-0.4.14 ruamel.y
aml-0.16.5 ruamel.yaml.clib-0.2.0 schema-0.7.1 tqdm-4.41.1
```

**Comment by mcgyver5** [comment]
I downgraded to 19.0.0 and the problem is not there.  Ashes is not a requirement in that version.  Put in pull request to add ashes to setup.py

**Comment by mcgyver5** [comment]
closed with pull request https://github.com/mahmoud/apatite/pull/2
